name: fireflyai
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  intl: ^0.18.1
  google_fonts: ^3.0.1
  get_storage: ^2.0.3
  image_picker: ^0.8.6
  image_cropper: ^3.0.2
  path_provider: ^2.0.14

  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.10

  firebase_core: ^2.11.0
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.6.0
  google_sign_in: ^5.4.2

  google_mlkit_barcode_scanning: ^0.5.0
  google_mlkit_image_labeling: ^0.5.0
  google_mlkit_text_recognition: ^0.5.0
  google_mlkit_language_id: ^0.5.0
  google_mlkit_translation: ^0.5.0
  google_mlkit_entity_extraction: ^0.6.0

  # google_ml_kit: ^0.13.0
  # firebase_storage: ^11.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
