name: fireflyai
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get: ^4.6.6
  intl: ^0.18.1
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  path_provider: ^2.1.1

  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.2.1
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  google_sign_in: ^6.1.6

  google_mlkit_barcode_scanning: ^0.10.0
  google_mlkit_image_labeling: ^0.10.0
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_language_id: ^0.9.0
  google_mlkit_translation: ^0.9.0
  google_mlkit_entity_extraction: ^0.11.0

  # google_ml_kit: ^0.13.0
  # firebase_storage: ^11.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/logo.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
